import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HeaderMenu } from "./components/header-menu";
import { Providers } from "./providers";
import { SnackBar } from "./components/snack-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <HeaderMenu />
          <SnackBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
